app_homepage:
    path:      /
    defaults:  { _controller: AppBundle:Default:index }

app_access:
    path:      /iniciarsesion
    defaults:  { _controller: AppBundle:Default:access }

app_register:
    path:      /registrarse
    defaults:  { _controller: AppBundle:Default:register }
    
app_verify:
    path:      /verificaremail
    defaults:  { _controller: AppBundle:Default:verify }

app_confirmation:
    path:      /confirmacion-registro
    defaults:  { _controller: AppBundle:Default:confirmation }

app_recover:
    path:      /recuperar
    defaults:  { _controller: AppBundle:Default:recover }

app_send:
    path:      /enviaremail
    defaults:  { _controller: AppBundle:Default:send }
